### PR TITLE
Spaces and pacman

### PR DESCRIPTION
**Pull request by danjones1618**
Spaces are horrid in the terminal and need escaping :cry: 
Also added the pacman installation command

### CODE REVIEW

**Comment by danjones1618** [comment]
Also added to .gitinore a pattern to ignore build directories in all directories

**Comment by drslock** [comment]
Are they really that problematic to work with ?
I don’t like the way underscores “look”
sneaking around at the bottom on the line like they are up to something

**Comment by drslock** [comment]
Maybe a bash script to replace spaces for people who don’t like them ?

**Comment by drslock** [comment]
Changes applied upstream (this repo is the output of automated build pipeline)

**Pull request closed without merging**
